spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_batch
    username:
    password:
    driverClassName: org.postgresql.Driver
  h2:
    console.enabled: true
#  batch:
#    jdbc:
#      initialize-schema: NEVER
#    job:
#      enabled: false