spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
#    job:
#      enabled: false
